version: '2'

services:

  payplh:
      image: 192.168.1.151:32000/payplh:1.11.122
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
